resolver: lts-7.8
packages:
- '.'
extra-deps:
  - simpleirc-0.3.1
  - posix-escape-0.1
  - tls-1.2.18
  - x509-1.5.1
  - x509-validation-1.5.2
  - asn1-parse-0.9.1
  - x509-store-1.5.0
  - x509-system-1.5.0
  - connection-0.2.4
flags: {}
extra-package-dbs: []
